version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run-script build
      - aws s3 cp s3://private-conf/mqp-site-ping/GeoIP2-City.zip .
artifacts:
  files:
    - dist/**/*
    - ./*.js
    - package.json
    - package-lock.json
    - GeoIP2-City.zip
  name: eb-build
  discard-paths: no

